### ISSUE TITLE
Does not seem to work in Safari (9.1.1+)

### ISSUE THREAD

**Issue by Nickersoft** [Nickersoft/push.js#1]

**Comment by geoffdavis92** [comment]
I'm also not seeing this in Chrome (Version 49.0.2623.112 (64-bit))

Loaded up the script from node_modules, placed it in head, and Push.js isn't working. No errors thrown, `Push` object shows up in Window object.

**Comment by Nickersoft** [comment]
I just pushed f4d8486c093def351caa8d113bb37849e128fca9 which seems to fix this issue (with both Safari and Chrome). I think I know what happened. In the request() method, legacy methods (no longer in either browser) were being checked for before methods in the current standard. I switched these two checks around and it seems to be working, at least on the [official site](http://nickersoft.github.io/push.js/demo.html). I think you might run into issues running it locally because of how browser permissions work (similar to how you can't run the Facebook API on a local site). Closing this ticket for now.
