### ISSUE TITLE
can push.js play audio when receive notification

### ISSUE THREAD

**Issue by zhujinhu21** [Nickersoft/push.js#100]
how to play audio  when receive notification.

**Comment by bramdebouvere** [comment]
I think it's best if you use an external audio library for this, such as Howler.js.

Or you might just do

`var a=new Audio('myFile.mp3');
a.play();`

**Comment by Nickersoft** [comment]
@bramdebouvere is right.. the JS Notifications API has no support for any kind of audio playback. Closing this for now.
