### ISSUE TITLE
 mismatch Version declared in the json (0.0.12) is different than the resolved one (0.0.13)

### ISSUE THREAD

**Issue by jy95** [Nickersoft/push.js#101]
When installed with bower : 
```bash
bower install push.js --save
```
I got this : 
```bash
bower push.js#*               mismatch Version declared in the json (0.0.12) is different than the resolved one (0.0.13)
```

**Comment by Nickersoft** [comment]
This isn't that surprising, as somehow the NPM and Bower version's have always been 0.0.1 version out of sync :( I thought I was able to resolve it but I guess not. Will look into it the next chance I can.

**Comment by Nickersoft** [comment]
This issue has been fixed in the latest release :)
