### ISSUE TITLE
Is link option really working ?

### ISSUE THREAD

**Issue by jy95** [Nickersoft/push.js#102]
Hello,

I was testing some options of Push.js when I found a bug : the link option doesn't seem to work.
Can someone explain me why ? 

I have something like this : 

```js
Push.create("Nouvel appel", {
            body: "un appel",
            requireInteraction: true,
            link: "/adminPanel?callId=2",
            icon: "/img/newCall.png",
            serviceWorker: "/bower_components/push.js/serviceWorker.js"
        });
```
I also discover for some reason the service worker is not listed in Application - Service Worker Tab from Chrome.

To check if it wasn't the path, I have done with the "old" way to register sw and it directly is shown on the tab: 
```js
navigator.serviceWorker.register('/bower_components/push.js/serviceWorker.js')
```
So what is wrong ?

My config : 

Chrome 58.0.3029.81 
Windows 10
Tested on your demo site

**Comment by cdiazgearlabs** [comment]
i have the same problem over here.Someone know why link option and serviceWorker aren´t working properly?.

Vibrate doesnt work either.

**Comment by Nickersoft** [comment]
Hi guys! Sorry I've been so absent from the issue board lately... been swamped with other work. The vibrate option should work, though I think there are some path issues pertaining to the ServiceWorker, as mentioned in #87. @cdiazgearlabs commented on that thread with what seems to be a temporary fix. I've added the "Help Wanted" label to this issue, as I believe this issue may be simple to resolve with some dabbling. However, in the event I may not have time immediately to pursue a fix, feel free to check out the issue yourself and see if you can get it working.

**Comment by Nickersoft** [comment]
Hi everyone! Just a quick update. Push v1.0 was released yesterday, with several new features and bug fixes. You now have the ability to set the service worker path in a global config, which you may have to do if your service worker file is not at the root of your web server (it's recommended that it should be to give it maximum operating scope). This should resolve any issues you have with the service worker not working. Push v1.0 is operational on the new homepage, https://pushjs.org, and the `vibrate` option seems to be working as expected. That said, the `link` option still isn't working as of v1.0.4, as I just found out by testing it on the homepage. Not exactly sure what the cause is. I'll try to investigate and get a fix out with the next release.

**Comment by manishshahi1** [comment]
Hi!
I think with my following code the link section will work:
try this:

    Push.create('Thank You!', {
        body: 'Thank you for subscribing!',
        icon: 'assets/images/monkey.png',
       // link: 'https://www.google.com',  // i have removed this part
        timeout: 6000,
        onClick: function () {
            window.open("https://www.google.com"); //just added the window.open to a OnClick event.
            this.close();
        },
        vibrate: [200, 100, 200, 100, 200, 100, 200]
    });

Hope it helps!

**Comment by ednihs-yahska** [comment]
The above solution does not work when browser is in background.

**Comment by hardcorp** [comment]
I found the below code worked for me in 
1) re-focusing back to the browser tab if focus is elsewhere, and 
2) re-directing to the href.
Hope it helps.

Push.create('Thank You!', {
    body: 'Thank you for subscribing!',
    icon: 'assets/images/monkey.png',
    timeout: 6000,
    onClick: function () {
        window.focus();
        window.location.href = "https://www.google.com";
        this.close();
    },
    vibrate: [200, 100, 200, 100, 200, 100, 200]
});

**Comment by tm-webentwicklung** [comment]
Hey, any update on this? Link option still not working in V1.0.9?

**Comment by chris-lawton** [comment]
To make the `link` option work you'll need a `serviceWorker.js` file that includes the code found in https://github.com/Nickersoft/push.js/blob/master/src/serviceWorker.js

**Comment by tm-webentwicklung** [comment]
So, despite the fact that the link option does not even work in the demo on pushjs.org, I've made a very simple demo script myself:
https://kunden.tm-webentwicklung.de/testarea/pushjs/pushjs.html

serviceWorker.js is located in my domain root 
https://kunden.tm-webentwicklung.de/serviceWorker.min.js

and also in my application root
https://kunden.tm-webentwicklung.de/testarea/pushjs/serviceWorker.min.js

and also in the subfolder one level above (just to make sure)
https://kunden.tm-webentwicklung.de/testarea/serviceWorker.min.js

and also in the same directory where the push.min.js script is located
https://kunden.tm-webentwicklung.de/testarea/pushjs/pushjs/serviceWorker.min.js 

My demo does not work. Whar am I doing wrong? I am on a Windows 8.1 machine with Firefox 67.0 and Chrome 74.

**Comment by theLufenk** [comment]
@tm-webentwicklung 
Please see: https://github.com/Nickersoft/push.js/blob/3ab2f79aa31966fd0ecbc675cc117c4b639ffa8b/src/push/Push.js#L215

The cause of your problem is that push.js defaults to using the Notification API rather than Service worker for creating a Notification in desktops.
Your example will run fine in Android chrome I reckon.

**Comment by tm-webentwicklung** [comment]
OK, but what does this mean? :) Does it mean, the Notification API does not support the link option in general?

**Comment by theLufenk** [comment]
@tm-webentwicklung Precisely. There is no support for a direct "link" option in either of the two Notification apis at browser level.
The onclick callback function is what you are looking at. You can see a possible implementation from the examples above by @manishshahi1  and @hardcorp .

Push.js too, uses the onclick callback internally to provide the link option.

Making the link option work without ServiceWorker should be straightforward to implement in Push.js too. A Pull Request is always welcome :)
