### ISSUE TITLE
Not working on Firefox but working on Edge.

### ISSUE THREAD

**Issue by biglobe** [Nickersoft/push.js#104]
"Every browser" being Firefox 22+, Chrome 5+, Safari 6+, Opera 25+, Android Browser 4.4+, Blackberry Browser 10+, Opera Mobile 37+, Firefox Android 47+, and Samsung Internet. Trying to get IE included on the list :) 

Despite the above statement, using the demo button on https://nickersoft.github.io/push.js/, this actually works on chrome and edge. However it does not work on Firefox 54.0 32-bit and 64-bit. It also did not work on an earlier 53.xxx version.

**Comment by Nickersoft** [comment]
Hi there! Thanks for using Push. I'm running OS X Sierra 10.12.5 and Firefox 53.0.3 (64-bit) and just tested the demo and it worked fine for me. Are you sure you've allowed Firefox to show notifications? You should be able to click next to the address bar and view the permissions for the site.

**Comment by biglobe** [comment]
looks like I really need to apologise for this false alarm. I tested it
again and it works now. Previously it does not even show the prompt to
enable notifications for the site.

**Comment by Nickersoft** [comment]
Hmm.. yeah I think it won't ask if the permissions for the site are already set. No worries! Closing this issue
