### ISSUE TITLE
How to focus/active tab(window) browser notification

### ISSUE THREAD

**Issue by KuTi** [Nickersoft/push.js#11]
Hi,

As the title. hope you help.

**Comment by alexcroox** [comment]
Did you find a solution for this? Would be useful to switch to the active tab onClick if it's possible?

**Comment by alexcroox** [comment]
The solution is

```
onClick: function() {
    window.focus();
}
```

**Comment by KuTi** [comment]
@alexcroox: thank reply :)

**Comment by ivanskins** [comment]
yes! thanks for solution

**Comment by m-oscartong** [comment]
@alexcroox Doesn't work for me. When there are multiple chrome windows, `window.focus();` will only focus on the latest active window. Also it can't focus back into the tab that sent the notification.
