### ISSUE TITLE
How do I send notifications to a at a set time every day without the user being on my website? 

### ISSUE THREAD

**Issue by SethuSenthil** [Nickersoft/push.js#113]
When I initially set this up I had to first set this up the notification appears when ever the site is loaded, but I was to send push notifications to the user every day at a set time also while they are not on the website?

**Comment by skortchmark9** [comment]
I believe you could do this with the service worker and a setTimeout call.

**Comment by theLufenk** [comment]
Push.js facilitates in creation of notification. In essence, it provides cross-browser wrappers over the Notification API.

How and when you create the notification is part of your application's logic. There are many ways you can achieve that. I can propose two:
1) Using the ServiceWorker to create a notification at an specific time.
2) Sending a push from you server
