### ISSUE TITLE
How i can change or remove the botton text?

### ISSUE THREAD

**Issue by FjBalsaVi** [Nickersoft/push.js#114]
I want to change this text
![push-js](https://user-images.githubusercontent.com/29286454/28991640-e7f0d9ba-798a-11e7-9539-fd1649ea59e2.jpg)

Thanks!

**Comment by Nickersoft** [comment]
As far as I know, this isn't possible giving the current Notifications API. Having the URL as part of the notification is the only way a user knows which website is sending the notification.

**Comment by FjBalsaVi** [comment]
Ok, thanks anyway.
