### ISSUE TITLE
Generate notifications to multiple users at the same time.

### ISSUE THREAD

**Issue by seansabe** [Nickersoft/push.js#115]
Greetings,

I'm new into web programming and I'm building a web application. The application works with a user loging system and depending on the user it will load an specific content to submit/edit. Everytime a user submits or edit data I want to generate a notification to all other users logged in the system. 

I don't know how I can reach this. What I've thought is that I could create a script somehow ( I don't know how) which constantly look for changes on the database. Then, I replicate this script in all the user content page so when the script checks for changes it will generate a notification to each user. I know this is not like a "host to everyone"-message and probably not the best idea but it will gerenate a notification from their own content.

I hope you understand my idea. If anyone can help me or guide me I will apreciate it. 
Sorry for my bad english.

**Comment by raybooysen** [comment]
I don't think this is a Push.JS issue and is really a design question for your application.  If you can make your application push down some information when any user submits or edit data, THEN you can use push.js to show notifications as per the examples.
