### ISSUE TITLE
Safari requestPermission() Promise not supported.

### ISSUE THREAD

**Issue by ellisio** [Nickersoft/push.js#117]
Hello,

According to the MDN, Safari does not support the `requestPermission().then()` Promise version.

Reference: https://developer.mozilla.org/en-US/docs/Web/API/Notification/requestPermission#Browser_compatibility

So when `Push.Permission.request()` is called in Safari users get the following error:

```
undefined is not an object (evaluating 'this._win.Notification.requestPermission().then')
```

Due to this block: https://github.com/Nickersoft/push.js/blob/master/src/classes/Permission.js#L34-L39

Cheers,
Andrew

**Comment by ellisio** [comment]
Hey @Nickersoft any update on this?

**Comment by Nickersoft** [comment]
Hi @ellisio! Sorry, I've been busy lately! You're totally right... I'll see if I can get a fix out by the end of the week. I think if the browser supports the promises API it throws a depreciation warning, so some extra logic will need to be added to prevent that. It's actually surprising, as Safari is one of the browsers testing this library on BrowserStack and all tests pass... maybe the permission tests need to be revisited.

**Comment by n3il** [comment]
This looks ... _promising_
https://github.com/Nickersoft/push.js/issues/120

**Comment by basiclines** [comment]
Looks like the official Safari web documentation uses a callback for the `requestPermission` function.

https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/LocalNotifications/LocalNotifications.html#//apple_ref/doc/uid/TP40012932-SW1

**Comment by n3il** [comment]
Very helpful @basiclines.

I'm still testing, but I opened this PR https://github.com/Nickersoft/push.js/pull/124.

**Comment by n3il** [comment]
So this PR (https://github.com/Nickersoft/push.js/pull/124) works and is tested against Chrome, Safari, and Firefox.

The Fix: Checking for Safari first means that it uses the callback method instead of the promise-based method which errors out. Assuming that it removes `webkitNotifications` entirely like Chrome did, the promise-based method will be used on a Safari update.

Also worth writing here that Safari is currently listed as having "No support" for promise-based Notifications.
https://developer.mozilla.org/en-US/docs/Web/API/Notification/requestPermission

**Comment by n3il** [comment]
@Nickersoft Thoughts?

**Comment by Nickersoft** [comment]
@n3il I went ahead a merged your PR (sorry I've been so busy lately.. taken me awhile to get around to it). I like your idea of a support table. I'll see if I can put one together and post it on pushjs.org.

**Comment by n3il** [comment]
@Nickersoft Thanks. I think we can close this ticket out then. Looking forward to it 👍

**Comment by Nickersoft** [comment]
Cool beans :) Thanks for the contribution @n3il!

**Comment by dsalzr** [comment]
I'm also getting this error:

undefined is not an object (evaluating 'this._win.Notification.requestPermission().then')

Looks like you committed some code to fix it. Are you planning on releasing 1.0.5 soon?

Thanks!

**Comment by camiloei** [comment]
Hi !

I'm getting this error on safari too: 

undefined is not an object (evaluating 'this._win.Notification.requestPermission().then')

any news about the status of this issue? I'll be glad to help if there's anything more to do to fix this problem.

Thanks!

**Comment by andjosh** [comment]
It seems the thinking here was that the `webkitNotification` API with callback-based permissions would be kept to support older Safari. The assumption was that Safari would not drop the deprecated `webkitNotification` API without also updating to the modern `Notification`/promise-based permissions API.

That didn't happen. :(

Safari (in Mojave, at least) dropped the webkit prefix but also still used the old callback-based permissions API.

**Comment by andresbravog** [comment]
this is still broken on last package version, can you release a new version?

**Comment by Shmasya** [comment]
Also not working in last version package.

**Comment by SohrabZ** [comment]
Any updates on this issue?

**Comment by tuborgbeer** [comment]
Safari is shit abandon this browser. Forward this issue to Apple they must fix one

**Comment by RajeshMalviya14** [comment]
this is working for me
if (Notification.permission === "granted") {
    console.log('allow', result);
return true;
}
if (!Notification.requestPermission()) {
      return true;
}
Notification.requestPermission().then(function (result) {
      if (result === 'denied') {
        console.log('denied', result);
        return;
}
if (result === 'granted') {
 console.log('allow', result);
}
}
