### ISSUE TITLE
Uncaught (in promise) PushError: permission request declined

### ISSUE THREAD

**Issue by vladyn** [Nickersoft/push.js#119]
I've got promise rejection in Chrome (Version 60.0.3112.113 (Official Build) (64-bit)) on Windows 7. This is on the landing page, where the Demo button is.

**Comment by bhaidar** [comment]
I started having the same issue too. Chrome 60.x on Windows 10.

**Comment by ak868308** [comment]
Try this

Push.config({ serviceWorker: '/<your js path>/serviceWorker.min.js'});

**Comment by imRohan** [comment]
Has this been fixed? I'm seeing the same error on Chrome Version 62.0.3202.75 (Official Build) (64-bit) ib Windows 7

**Comment by visionding** [comment]
I have the same error on Chrome 63.0.3236.0 (64-bit) Windows 10

**Comment by bram1028** [comment]
I'm getting this too. It worked fine on localhost, but is failing in production. I tried the serviceWorker and no change. I manually added my production domain to the allowed list, and still same error.

**Comment by newmandani** [comment]
Chrome 62.0.3202.89 (Official Build) (64-bit)
Incognito mode:
![image](https://user-images.githubusercontent.com/5398572/32782346-24589168-c959-11e7-9924-4e5a5fa47866.png)

Normal mode:
![image](https://user-images.githubusercontent.com/5398572/32782397-514b3518-c959-11e7-9eb5-7f51860070b5.png)

and some time:
![image](https://user-images.githubusercontent.com/5398572/32782492-a59fe884-c959-11e7-936f-5358cffbdff1.png)

**Comment by ommeirelles** [comment]
I was having the same error as @bram1028. Worked fine in firefox and chrome localhost but in chrome production got the error. Strange that last week was working just fine for me. 
I resolved the error by accessing my production through https. Looking for serviceWorker tutorial from google they say that is only possible use it in productions through https..

**Comment by projct1** [comment]
Save issue with `Version 62.0.3202.94, 64 bit`.

**Comment by Thx3r** [comment]
Hi, it's not an code error.
Since new Chrome version Notification have to bieng use by "Secure Origins".
So, if you want use Notification http address muste be : **localhost** OR **https://**

I you want you cant also start chrome with cmd line with this line : -unsafely-treat-insecure-origin-as-secure="http://example.com"

You can try Notification via native Html5 : new Notification("hello") 

Have a nice day.

More info here : https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

**Comment by projct1** [comment]
Yea, thanks, problem was solved by move to https.

**Comment by shahab2058** [comment]
The demo given on the https://pushjs.org/ page has the same issue mentioned in the title. I am facing the same issue.
