### ISSUE TITLE
Bower packgage

### ISSUE THREAD

**Issue by badlamer** [Nickersoft/push.js#12]
Please, create bower package!

**Comment by Nickersoft** [comment]
Should be an easy addition. Will look into it :)

**Comment by edgaraafelix** [comment]
Any update on the bower package? Is  it being implemented?

**Comment by Nickersoft** [comment]
I should be able to do it tomorrow!

**Comment by Nickersoft** [comment]
@edgaraafelix Bower now available! Try `bower install push.js`.
