### ISSUE TITLE
Return a Promise in Push.Permission.request instead of using callbacks

### ISSUE THREAD

**Issue by basiclines** [Nickersoft/push.js#120]
Maybe we can return a promise here in order to have an implementation more similar to the native solution instead of using callbacks.

https://github.com/Nickersoft/push.js/blob/c990321f90e1a205cafadc03809018cba7692c36/src/classes/Permission.js#L44

I can make a PR if you agree with this but it will need some triage to see which version should adpot this kind of improvements.

**Comment by Nickersoft** [comment]
I like the way you think... I say go for it! At first I was worried about compatibility, but Push has adopted promises across several methods at this point, so I see no problem with this :)
