### ISSUE TITLE
integrate with sockjs and my websocket

### ISSUE THREAD

**Issue by ghost** [Nickersoft/push.js#123]
I have an chat application ,i using sockjs for connect to my websocket that implement by java spring websocket  framework. how can i use push.js and integrate with my websocket channel and show  new messages ?

**Comment by Nickersoft** [comment]
Hi @azizkhani! Thanks for using the library! You have a couple options, actually. You could either stick a `Push.create()` call inside the code block that executes when the client receives a new message from the server, or you could push notifications from the server side when the client sends a message. This allows notifications to be shown even when the browser is closed and uses Firebase Messaging to do so, but of course you'll need the official [Push FCM plugin](https://github.com/Nickersoft/push-fcm-plugin) and a Firebase account if you choose that route.
