### ISSUE TITLE
[Question] Does this work on mobile browsers?

### ISSUE THREAD

**Issue by James2516** [Nickersoft/push.js#125]
Does this allow push notification to Safari on iOS and Chrome/Firefox on iOS & Android?

**Comment by ZiadJ** [comment]
From the link below it seems Chrome, Safari and IE don't not support it on mobiles: 
http://caniuse.com/notifications/embed/eras=-3,&description&links

Firefox 55 on Android supposedly does but I haven't had any luck with the demo button on pushjs.org

**Comment by theLufenk** [comment]
As of now, there's no support for Push notification at all on iOS. 
Chrome and Firefox both support Push.js on Android.
