### ISSUE TITLE
Not working in chrome

### ISSUE THREAD

**Issue by ak868308** [Nickersoft/push.js#126]
Hi All,
I don't know whats wrong with me. Push.js is working fine in mozilla for both (desktop/mobile) but not working for chrome while on desktop chrome it is working like a charm but for mobile chrome it never shows an error & not a notification.
Here is my code:

`Push.config({serviceWorker: '/js/alerts/serviceWorker.min.js'});
            Push.create('XYZ is online', {
                body: 'You can contact him now',
                icon: '/images/logo.png', 
                link: '#',
                requireInteraction: false,
                tag: 'online-alert',
                vibrate: [200, 100] 
            }).catch(function(e) {
                console.log(e);
            });`

Please help if there is any fix
Thanks

**Comment by Nickersoft** [comment]
Is your site HTTPs? Mobile Chrome requires service workers to show notifications properly, and will only allow notifications that are SSL-encrypted (begin with https:// not http://). It should theoretically work on http:// sites in any other browser, just not Mobile Chrome.

**Comment by k0t0fey** [comment]
Have the same problem. And yes, my site https.
I generally do not understand how the button works on the demo page in mobile chrome. Full cloning of this page does not work. In addition, there is no code on the demo page that connects the serviceWorker...
My clone of demo page: [https://shikari.do/push.html](https://shikari.do/push.html)

**Comment by Nickersoft** [comment]
@k0t0fey I ran your site on my phone and checked Chrome's inspector and saw the following error:

```
TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.
```

From the sounds of things, it can't find any service worker. The most common fix for this is specifying a custom path to the service worker via the `serviceWorker` config option. See the bottom of [this page](https://pushjs.org/docs/options) for more info on this.

**Comment by k0t0fey** [comment]
Finally, it worked only after I placed the minified service worker file in the root of the my site.
If specify a different path through the settings (Push.config), it does not work.

**Comment by Nickersoft** [comment]
@k0t0fey I think this might have to do with the scoping issue mentioned in #87. However, that problem was discussed before v1.0 and before the `serviceWorker` config option was available, so perhaps the config option isn't working? Could you shed some light on which paths you were passing to the option, the path you're calling Push from, and any errors that are being thrown?

**Comment by mikeshow** [comment]
Hi,

In Chrome 62 I get that error:

Uncaught (in promise) PushError: permission request declined

In Chrome Canary 64, IE, Edge, Fiefox, Opera it works.

Mike.

**Comment by ak868308** [comment]
@mikeshow please place your serviceWorker.js in web/ director. Means in a root directory.

**Comment by 1Rhino** [comment]
Me too.
`Chrome Version 62.0.3202.75 (Official Build) (64-bit) - MacOS 10.12.6`
Error:
`Uncaught (in promise) PushError: permission request declined`

Firefox, Safari worked :(

**Comment by Nickersoft** [comment]
Guys, I finally got a chance to look at this issue. I'm using Chrome 62.0.3202.89 on Windows 10 and the demo on pushjs.org works just fine. Are you sure you didn't accidentally deny permission for the entire webpage? If you click in the green area next to the URL, you can select whether to always allow or always deny permissions for that page. If it's set to deny, this error may occur. I would check your browser settings.

**Comment by izll** [comment]
https://www.chromestatus.com/feature/5759967025954816
In chrome 62 the insecure usage of notifications removed :(

**Comment by Nickersoft** [comment]
@izll I think that would explain a lot

**Comment by projct1** [comment]
Same issue with `Version 62.0.3202.94 (Official Build) 64 bit Windows 10`.
http://joxi.ru/l2ZVP4EH8GyWR2
http://joxi.ru/a2XeBzEUyok57A

**Comment by theLufenk** [comment]
Notification permission cannot be granted to an insecure origin (expect localhost) in Chrome.
This doesn't seem like a bug in Push.js by itself. Closing.

**Comment by amanprofsys** [comment]
Hi @Nickersoft , you made a great liberary for sure and i respect your work but can you help me i am not able to use this notification on android smartphones. Please help.
Thanks.
