### ISSUE TITLE
[Suggestion] Trigger push notification only if user is not viewing page

### ISSUE THREAD

**Issue by lifenautjoe** [Nickersoft/push.js#128]
**TLDR;** Add an option to `Push.create({ onlyAway: boolean })` to display the notification only if the user is away from our page using the [visibility API](https://stackoverflow.com/a/19519701/2608145).
____

### Example Usecase

**A file transfer failure/success notification.**

We would like to notify the user when his upload has been completed or failed instead of him checking continuously the status.

We would not however like to notify the user of this situation if the user is already on the page and therefore can already see that something has happened.

**Comment by Nickersoft** [comment]
Hey @lifenautjoe! I like the way you think. I'll look into it :) In the meantime, the [Firebase Cloud Messaging plugin](https://github.com/Nickersoft/push-fcm-plugin) I wrote a few months ago for Push should allow you to only send notifications when the tab is not focused.

**Comment by lifenautjoe** [comment]
Hey @Nickersoft , thanks! and good to hear you like the idea.

In my own project I am using [Visibilityjs](https://github.com/ai/visibilityjs). Great library for multibrowser support. 

If you have no time I could try making some time and help out. We would just need to know in advance if we are using a library such as visibilityjs or our own code to detect when a user is away.

**Comment by Nickersoft** [comment]
Hi @lifenautjoe, sorry it's been awhile since visiting this post. Work has had been swamped the past month or so, so if you still think this functionality is worth having, I'd encourage you to go ahead and look into opening a PR :)
