### ISSUE TITLE
Cannot find module '+s+'

### ISSUE THREAD

**Issue by cryptofuture** [Nickersoft/push.js#137]
Trying to use it
```js
var Push = require('push.js');
Push.create('Hello World!');
```
```js
!function(t){if("object"==typeof exports&&"undefined"!=typeof module)module.exports=t();else if("function"==typeof define&&define.amd)define([],t);else{("undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:this).Push=t()}}(function(){return function t(e,n,i){function o(s,a){if(!n[s]){if(!e[s]){var u="function"==typeof require&&require;if(!a&&u)return u(s,!0);if(r)return r(s,!0);var c=new Error("Cannot find module '"+s+"'");throw c.code="MODULE_NOT_FOUND",c}var f=n[s]={exports:{}};e[s][0].call(f.exports,function(t){var n=e[s][1][t];return o(n||t)},f,f.exports,t,e,n,i)}return n[s].exports}for(var r="function"==typeof require&&require,s=0;s<i.length;s++)o(i[s]);return o}({1:[function(t,e,n){"use strict";Object.defineProperty(n,"__esModule",{value:!0});n.default={errors:{incompatible:"PushError: Push.js is incompatible with browser.",invalid_plugin:"PushError: plugin class missing from plugin manife
TypeError: Cannot read property 'Notification' of undefined
```

**Comment by Nickersoft** [comment]
What environment are you using it in? Node?

**Comment by cryptofuture** [comment]
Using it with node `v6.12.0` and loopback3

**Comment by Nickersoft** [comment]
Any reason you're trying to use it in Node? Push creates notifications from the client-side and requires the Notification API (or ServiceWorkers) to create notifications, which isn't available in Node.

**Comment by cryptofuture** [comment]
Is it possible to use it with https://github.com/wikimedia/node-serviceworker or https://www.npmjs.com/package/node-service-worker to force notifications show in browser when some event/condition happens on server?

**Comment by Nickersoft** [comment]
That's a question I get a lot, and while Push.js is designed to only run on the client-side, the functionality you're suggesting is possible using the [Push FCM plugin](https://github.com/Nickersoft/push-fcm-plugin). I'd take a look and see if you get it working using that.

**Comment by cryptofuture** [comment]
Thanks for help and making it clear! Sadly sharing data with google services is not an option.

**Comment by Nickersoft** [comment]
Your second best option would be to have Push run in the browser and have your client communicate to your backend using sockets (a good tool is [socket.io](https://socket.io/)). Then, when the client receives messages from the socket, it'll send a notification. Unfortunately, this still requires the browser to be open for the notifications to appear. Sorry for the inconvenience!
