### ISSUE TITLE
Close tab and then Click on notification

### ISSUE THREAD

**Issue by nunoperalta** [Nickersoft/push.js#143]
Hello,

If a notification opens and then I close the tab that originated that notification, the notification does not seem to do anything when I click.

See "onclick" code below. Not even the "alert(1)" shows.

Is there any workaround for this? I'd like to make it open a new window if the current tab doesn't exist anymore. Thank you.

`onClick: function() {  
	alert(1);  
	maybeAjax(link);  
	window.focus();  
	this.close();  
}`

**Comment by Nickersoft** [comment]
This is most likely due to the fact that the JavaScript callback function exists within the open tab. Once you close it, it destroys that code and so the notification doesn't do anything when it's clicked. The workaround for this is Service Workers, which Push does support, however, Service Workers are only used for mobile browsers. The Notification API is used for most desktop browsers.

**Comment by nunoperalta** [comment]
Thank you. I understand and that's what I was assuming.

However, if I do the same on Facebook, i.e., I receive a notification (on Windows, Google Chrome), and then close the tab that triggered it,
the notification will open a new tab.

Is this because Facebook is only using service workers?


Is there any way that I can trigger a notification directly through a service worker using Push.js? Or is this only possible by using the Push API?

Thank you.

**Comment by Nickersoft** [comment]
I should probably incorporate a way users can force it to use Service Workers, however, right now you can't :/ That said, the codebase is fairly easy to navigate, so you could look into opening a PR if you want.

**Comment by nunoperalta** [comment]
Thank you. I'm actually learning about service workers as I write. I've just succeeded doing the above through postMessage, and using the event "onmessage" on the service worker :)

**Comment by Nickersoft** [comment]
Good to hear! And actually, if you look [here](https://github.com/Nickersoft/push.js/blob/master/src/agents/MobileChromeAgent.js#L86) and [here](https://github.com/Nickersoft/push.js/blob/master/src/serviceWorker.js#L24) you'll notice that Push uses the same kind of approach.  The [MobileChromeAgent](https://github.com/Nickersoft/push.js/blob/master/src/agents/MobileChromeAgent.js) is actually the only Push agent that uses Service Workers (if my memory serves me right), so all that would be required is to add a Push config option that forces the library to use that specific agent (off by default, of course).
