### ISSUE TITLE
Not working on Mobile Chrome (Android 63.0.3239)

### ISSUE THREAD

**Issue by puckpuck85** [Nickersoft/push.js#144]
Hey, on Android Chrome it doesent work (it ask's the first time for permission but no push notifications pops up) when i'm visiting with the same browser your site, it works perfect. 

so for testing cloned your site, but it doesnt work under chrome - firefox for android works like a charm - same on desktop.

this is the testpage: https://secretcandy.net/push.html

serviceWorke is in root of webdirectory:;
https://secretcandy.net/serviceWorker.min.js

so, after 8 hours of try and error i dont know more what i can do... please help me.

cheers, puck

ps: or do i need the firebase stuff you use on your page???

**Comment by Nickersoft** [comment]
Hey @puckpuck85, so I just debugged your site using Chrome's inspector tool on my phone (for info on how to do that, [see here](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/)). Upon loading your page, I immediately got the following console errors:

```
> The script has an unsupported MIME type ('application/octet-stream').
> push.html#:1 Uncaught (in promise) DOMException: Failed to register a ServiceWorker: The script has an unsupported MIME type ('application/octet-stream').
```

Inspector your page further, I noticed that all your JS files contained a `Content-Type` header of `application/octet-stream`, which is incorrect. They should be `application/javascript`. You'll have to configure your server to change this heading, then the service workers should load. Browsers are very strict when it comes to loading service workers. Let me know if you have any other questions or concerns, and thanks for using Push!

**Comment by puckpuck85** [comment]
hey Nickersoft,

thank you so much for this hint. 

this was the problem -> mime type assign in lighttpd was set wrong/missing. what i did to fix this:

changed this in the /etc/lighttpd/lighttpd.conf 
commented out this line -> 
# include_shell "/usr/share/lighttpd/create-mime.assign.pl" 

and added this: 

mimetype.assign = (
  ".html" => "text/html", 
  ".txt" => "text/plain",
  ".jpg" => "image/jpeg",
  ".png" => "image/png", 
  ".css" => "text/css",
  ".js"  => "text/javascript"
)

now, it works.

**Comment by Nickersoft** [comment]
Glad you got it working!
