### ISSUE TITLE
index.d.ts is not included in published package

### ISSUE THREAD

**Issue by clarkorz** [Nickersoft/push.js#147]
I see there is a typing file in source, but installed package doesn't include it.

**Comment by Nickersoft** [comment]
@clarkorz Oh wow, you're absolutely right! Hard to believe no one caught that until now. The types were added all the way [back in October](https://github.com/Nickersoft/push.js/pull/129). I was getting ready to go ahead and add `index.d.ts` to the package (which is controlled by the [package.json `files` property](https://github.com/Nickersoft/push.js/blob/master/package.json#L15)) when it occurred me that I myself am not that familiar with TypeScript, and thought it would be worth discussing how this file should appear in the final package. Currently, only the `bin` directory is exported.. should `index.d.ts` be copied there or remain in the directory root? Should it keep its name or should it become `push.d.ts` or something to make it more clear what the purpose of the file actually is? Pinging @lifenautjoe who did the original PR in case he feels like offering his insight as well.

Once this decision is made, pushing out the new version should be a piece of 🍰

**Comment by theLufenk** [comment]
A [PR](https://github.com/Nickersoft/push.js/pull/183) has been added for this.
@chriswiggins can you please clarify on the few question that @Nickersoft asked above.

I can go ahead and merge the PR. But, does a minor patch release for just this makes sense ?

**Comment by chriswiggins** [comment]
Hey team,

Typically most modules just use index.d.ts as the filename and it should be in the module root. 

I bumped the package version for two reasons: 1) the last github tagged release didn’t update the package.json version, so npm is theoretically one behind. 2) without bumping the minor number and releasing then no one will get the typescript definitions until next time something is released. If you’re happy with that then that’s cool but I don’t see a reason you wouldn’t bump and release. Version numbers are cheap!

Let me know if you need anything else!
