### ISSUE TITLE
Documentation incomplete

### ISSUE THREAD

**Issue by roshin8** [Nickersoft/push.js#149]
You didn't mention that we have to include the javascript **push.min.js** in our html. Without including that, it will throw error

**Comment by roshin8** [comment]
Can we use Push.create in our nodejs main app.js file?
I tried const Push = require('push.js')
It's not working. It says Push is undefined

**Comment by Nickersoft** [comment]
Push is used for creating notifications on the client-side. Calling `Push.create()` from the server-side won't do anything.

**Comment by roshin8** [comment]
So you don't really need to run this on node server right? You can just run this on any server as it doesn't have any dependencies with node.
Also, why isn't including the push.min.js or push.js file in the html as Javascript source mentioned in the documentation?

**Comment by Nickersoft** [comment]
@roshin8 Push is designed for client-side use only. Server-side JavaScript doesn't contain the APIs required for Push to run, so it should never be used on a server. If you _do_ want to send Push notifications from the server, I suggest you check out the [push-fcm-plugin](https://github.com/Nickersoft/push-fcm-plugin) which lets you do so with Firebase. As for including `push.min.js`, it's the main file specified in `package.json` so I guess I thought it was assumed. I double-checked the docs and it does say you need to include it [on the plugins page](https://pushjs.org/docs/plugins), but maybe that should be moved to somewhere more prominent.

**Comment by roshin8** [comment]
Got it. Thanks a lot!
