### ISSUE TITLE
Service worker is not loading

### ISSUE THREAD

**Issue by herkyl** [Nickersoft/push.js#153]
I am trying to get Push.js to work on Chrome for Android. However it is never even trying to load the service worker script. What could be wrong?

Live example: https://scaledrone.github.io/html5-javascript-push-notifications/
Code: https://github.com/scaledrone/html5-javascript-push-notifications/

**Comment by Nickersoft** [comment]
Hey @herkyl... I tried your site, and you're correct that no notifications are being shown. I sent that cURL request from my terminal and no notification showed. However, there was also no output at all in my Chrome dev console. I tried this from my desktop, and by default Chrome desktop should be using the Notifications API, with which I still got nothing. Are you sure your `.on()` message listeners are firing correctly?

**Comment by theLufenk** [comment]
@herkyl At present, Push.js registers a service worker only on mobile Chrome. In desktops, it uses the Notifications API as @Nickersoft mentioned above. I assume you have solved the  problem with your code since I can now see notifications in the link you have provided above.
