### ISSUE TITLE
there are no options like image, tag, button?

### ISSUE THREAD

**Issue by programmerpsk** [Nickersoft/push.js#156]
I heard pwa push notification have many options like below.

1. image
![image](https://user-images.githubusercontent.com/25639099/35209598-2d9672d0-ff92-11e7-9e5f-924dcef4d326.png)

2. tag
![tag2](https://user-images.githubusercontent.com/25639099/35209651-5f4860fe-ff92-11e7-9695-55c87bacc602.png)

3. button
![actions](https://user-images.githubusercontent.com/25639099/35209594-27021398-ff92-11e7-96b3-1b01454791a0.png)

but push.js doesn't have this attr..
Is it right? there are not options like this?

**Comment by Nickersoft** [comment]
Hey @programmerpsk, I believe these features have limited browser support, which may be why they were not actively considered when Push launched. Checking the Mozilla site:

- `Notification.image`: Chrome, Firefox (with `-moz-` prefix), and Opera
- `Notification.actions`: Chrome & Opera

That said, perhaps it is worth exploring.

As for tags, unless you're referring to a different kind of tag, Push supports tags via the `tag` option (see [here](https://pushjs.org/docs/options) and [here](https://github.com/Nickersoft/push.js/blob/06796d49ffef8b6a4a43e4cd1a906f91282a735d/src/agents/DesktopAgent.js#L34)).

**Comment by programmerpsk** [comment]
I see. Thanks for your answer~!
