### ISSUE TITLE
addEventListener is not a function

### ISSUE THREAD

**Issue by owen2345** [Nickersoft/push.js#159]
Sharing a experience: I had this error because I had another class called "Notification" in my project (there was a conflict). I solved this by renaming my class into other name.

**Comment by theLufenk** [comment]
`Notification` is an API exposed by the browsers. Push.js never modifies this Object but rather uses it for for creating Notifications, etc.
Overriding the browser's Notification object with your own, will hence cause Push.js to become non-functional.
