### ISSUE TITLE
how to integrate push js with vue 

### ISSUE THREAD

**Issue by northerchild** [Nickersoft/push.js#169]

**Comment by chris-aeviator** [comment]
@northerchild 

I suggest to use vue-loader (included if you install vue cli) and add it as a dependency to your package.js file or run `yarn add push.js`. This way you can access push.js in your vue *js files* like so:

```
import push from 'push.js'
push.create('Hello World')
```

**Comment by northerchild** [comment]
Thansk dude @chris-aeviator

**Comment by deepthan** [comment]
same with angular
