### ISSUE TITLE
What is the purpose for the "link" and "serviceWorker"?

### ISSUE THREAD

**Issue by kurokami98** [Nickersoft/push.js#173]
The link is not working tho...

And also may i know what is "serviceWorker"? I am very blur on this stuff :/

**Comment by db-dzine** [comment]
https://developers.google.com/web/fundamentals/primers/service-workers/

**Comment by theLufenk** [comment]
The 'link' option lets you specify a relative URL path. When the user clicks on a generated notification on Mobile, he will be navigated to this URL in the browser.

Please refer to [Documentation](https://pushjs.org/docs/options).
