### ISSUE TITLE
Using Existing Service Worker

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [Nickersoft/push.js#176]
I'm using Push.js along with the FCM plugin. I already have a service worker set up that handles a bunch of other stuff and Push.js is over-writing my existing service worker with serviceWorker.min.js.

What's the proper way of including serviceWorker.min.js functionality via importScripts() in my master service-worker.js? I'd like to import it in another service worker and prevent Push.js from loading it.

**Comment by a-eid** [comment]
```
Push.config({
    serviceWorker: './customServiceWorker.js', // Sets a custom service worker script
    fallback: function(payload) {
        // Code that executes on browsers with no notification support
        // "payload" is an object containing the 
        // title, body, tag, and icon of the notification 
    }
});
```

**Comment by theLufenk** [comment]
Please refer to the [documentation about configuration options](https://pushjs.org/docs/options#configuration-options). 
You can specify a custom service worker as @a-eid has comments above.
