### ISSUE TITLE
list of data passing

### ISSUE THREAD

**Issue by sundar9511** [Nickersoft/push.js#177]
When i pass a list of data in a for loop of 10 only 3 is loaded rest of the notification not shown i pass it like.
var arraylist;
angular.forEach(arraylist ,function(a,index){
Push.create("Hi there",{
            body: "" + a.some,
            icon: 'Images/Target-Logo.png',
            timeout: ""+ i,
            onClick: function () {
                  $state.go('app.form.asd')
            }
        });
}

**Comment by theLufenk** [comment]
Displaying a Notification is eventually handled internally by the OS. Creating multiple notifications in a short period of time will result in different behaviours across Platforms and Browsers.
If you are using Mac or newer versions of Chrome on Windows, the notifications are sent to the Notification Center and Action Center respectively. I suggest checking there for the notifications that were not displayed.

It is more of a UX decision by the vendors as opposed to something is handled by Push.js 

I do not know of your use case, but wrapping the notifications in a suitable Timeout **might** be useful if you really want to bombard the user with 10 simultaneous notifications. And then too, the behaviour is governed by the Environment the user is in.

Please feel free to reopen the issue if the reply is not satisfactory or you believe there's a bug on the end of Push.js. Thanks
