### ISSUE TITLE
Enhancement / Wishlist

### ISSUE THREAD

**Issue by sarbbottam** [Nickersoft/push.js#18]
It would be great to adopt the following practices 
- [ ] use [xo](https://github.com/sindresorhus/xo) to lint the code.
- [ ] [use conventional commit message](https://github.com/sarbbottam/write-an-open-source-js-lib#writing-conventional-commits-with-commitizen)
  - [ ] [enforce conventional commit message](https://github.com/sarbbottam/eslint-find-rules/blob/master/package.json#L79)
- [x] [semantic release](https://github.com/sarbbottam/write-an-open-source-js-lib#automating-releases-with-semantic-release)
- [x] [Use ES2015](https://github.com/sarbbottam/write-an-open-source-js-lib#adding-es6-support)
- [ ] [let the browser compatible version be generated](https://github.com/sarbbottam/write-an-open-source-js-lib#add-a-browser-build-to-an-npm-module)

**Comment by testerdvest** [comment]
Fhfhf

**Comment by theLufenk** [comment]
1) Push.js uses eslint, which as it stands, is the most popular linting tool right now. 
2) Commit messages should indeed follow the standard convention. Completely agreed. I would try to ensure merges to master follow the conventions.
3) Push.js is already using semver for releases.
4) Push.js is wriiten in ES2015.
5) Rollup is our build tool which has been configured to spit UMD builds.

Grateful for your recommendations @sarbbottam  :)
