### ISSUE TITLE
bin/push.js was removed in v1.0.6, breaking others packages

### ISSUE THREAD

**Issue by ncoden** [Nickersoft/push.js#180]
Hi,

`bin/push.js` was removed in https://github.com/Nickersoft/push.js/commit/06796d49ffef8b6a4a43e4cd1a906f91282a735d when switching to Rollup.

Others packages (like https://github.com/devotox/ember-cli-pushjs) rely on this file and are now broken. If this is intentional, this should come in a new major version, not a patch one (https://semver.org/).

Could you add these files back ?

Thank you

**Comment by ncoden** [comment]
poke @Nickersoft

**Comment by Nickersoft** [comment]
Hey @ncoden! Thanks for reporting. Not sure I managed to miss such a major breaking change. Just pushed out an emergency release (v1.0.7) though that adds this file back!

https://github.com/Nickersoft/push.js/pull/181

**Comment by ncoden** [comment]
Thanks a lot @Nickersoft. Closing this issue.
