### ISSUE TITLE
One code example or Docs...

### ISSUE THREAD

**Issue by anthonybudd** [Nickersoft/push.js#185]
There are no code examples.

On the Docs page you just have random methods, with no context.

Please add at least one code example to the readme.md that has the following:
1. The import statment
2. How to initialise the Push.js
3. Call  method

**Comment by Nickersoft** [comment]
You don't initialize it. It's a static class, so it really is as simple as just running

```javascript
Push.create("Hello world!", {
    body: "How's it hangin'?",
    icon: '/icon.png',
    timeout: 4000,
    onClick: function () {
        window.focus();
        this.close();
    }
});
```

(from the Quick Start page). As for importing, a script tag can be added to the page, even from a CDN:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/push.js/1.0.7/push.min.js" />
```

Or you just use the default export like so:

```javascript
import Push from 'push.js';
// or
const Push = require('push.js');
```

It's so simple I didn't deem it necessary to elaborate any further in the docs.
