### ISSUE TITLE
License not preserved in minified library

### ISSUE THREAD

**Issue by Nickersoft** [Nickersoft/push.js#19]
The current uglify implementation removes all comments, including the license and attributions at the top of the file. Investigate into fixing, either via command-line tools or the reinstallation of gulp (with the gulp-uglify package).

**Comment by sarbbottam** [comment]
Ohh, my mad I can take this up tomorrow, https://www.npmjs.com/package/bannerize would be useful.

**Comment by Nickersoft** [comment]
Sounds good. I'll assign the issue to you.

**Comment by Nickersoft** [comment]
To be fixed by #24
