### ISSUE TITLE
typescript error

### ISSUE THREAD

**Issue by tony-gutierrez** [Nickersoft/push.js#191]
ERROR in node_modules/push.js/index.d.ts(3,20): error TS2714: The expression of an export assignment must be an identifier or qualified name in an ambient context.

**Comment by VicXXX** [comment]
I think it was merged already.

**Comment by tony-gutierrez** [comment]
Still not right in .08

ERROR in node_modules/push.js/index.d.ts(3,20): error TS2714: The expression of an export assignment must be an identifier or qualified name in an ambient context.

**Comment by theLufenk** [comment]
@tony-gutierrez @ukon1990 
A PR fixing the issue has been merged. The change would be pushed to npm very soon. I apologise for the inconvenience.

**Comment by theLufenk** [comment]
Just released v1.0.9. Should be fixed now.
Closing the issue.
