### ISSUE TITLE
README not included in NPM package

### ISSUE THREAD

**Issue by Nickersoft** [Nickersoft/push.js#20]
I believe this is required for an up-to-date description on the NPM package page, so the README should be re-added to the distributed package.

**Comment by sarbbottam** [comment]
Strange!!
* package.json
* README (and its variants)
* CHANGELOG (and its variants)
* LICENSE / LICENCE

[Should be part of the package by default](https://docs.npmjs.com/files/package.json#files ).

If I rename the file, to `readme.md` it works, I have no clue.

**Comment by sarbbottam** [comment]
Bug in npm, please see https://github.com/npm/npm/issues/5082#issuecomment-220172560

> I highly recommend using Node.js 4 LTS (via nvm or nave, if you don't want to use it the rest of the time) to publish.

As suggested may be release needs to be carried out in Node.js 4.

**Comment by Nickersoft** [comment]
Corrected in #25
