### ISSUE TITLE
Push.Permission.request not functioning correctly?

### ISSUE THREAD

**Issue by sbell9** [Nickersoft/push.js#203]
Hello,

I'm trying to use push.js inside of a Vue.js component. I added push.js to my project using npm and am importing it into my component like this:

`    import push from 'push.js';
`

I then ask for permission like this:
```
mounted: function () {
            push.Permission.request(this.onGranted(), this.onDenied());
        },
```

I'm noticing that when this component loads in the browser, the two callback functions (onGranted, onDenied - both just console log stuff for now) are being called at the same time as when the permission request window pops up. In the request popup, regardless of which button I push, neither of those functions seem to get called.

**Comment by theLufenk** [comment]
Hey @sbell9 
The `request` method is expecting references to function as it's two arguments, which will be called on the permission being granted and denied.

Are `this.onGranted` and `this.onDenied` the callbacks you want or do they return a function that you want as the callbacks ?

Your problem can **probably** be solved by **not calling** the callbacks functions and passing them directly instead.

Please change the statement to `push.Permission.request(this.onGranted, this.onDenied);` and see if that works for you.

**Comment by sbell9** [comment]
That was it, thank you
