### ISSUE TITLE
Is there a way to add timestamp to show notification  for user, even though it's not on the site anymore?

### ISSUE THREAD

**Issue by GaidenX** [Nickersoft/push.js#206]
Example: 
I need to show a notification after the user go out of my website and this notification can be show hours after in the same day or maybe in another day to bring back my user. Like a timestamp to show.

It's be possible? Someone can help me? Thanks.

**Comment by theLufenk** [comment]
This is not possible atleast in a straightforward manner with the current implementation of Push.js.
You might want to look into service workers and server-side push notifications.
