### ISSUE TITLE
Data to pass to ServiceWorker notifications ?

### ISSUE THREAD

**Issue by masgun** [Nickersoft/push.js#207]
Hi, could you please explain more about how and what to pass to ServiceWorker notification ?

what I want to do: 
I want to create a desktop notification when the tab or even the browser is closed.
I could not find any documentation or code example of that yet. So far I dig here, I realize that we must put something to ServiceWorker to make the magic available, so please advice.
thank you..

**Comment by theLufenk** [comment]
This is not possible atleast in a straightforward manner with the current implementation of Push.js.
You might want to look into service workers and server-side push notifications.
