### ISSUE TITLE
Coloring the notification

### ISSUE THREAD

**Issue by nimasfl** [Nickersoft/push.js#209]
Hi.
I'm wondering if is there any way to somehow change the color of notifications ?

**Comment by theLufenk** [comment]
Color of what specifically ?

**Comment by nimasfl** [comment]
I'm using push.js for windows desktop notification. the background color of notifications on windows 10 is too white. in addition to it, I'm using arabic language for notification body and the default font is so ugly.
I'm looking for a way to change background color and default font of windows desktop notifications.

**Comment by theLufenk** [comment]
No that is not possible according to the Notifications API spec.
