### ISSUE TITLE
Update notification body content without animating new notification in it's place

### ISSUE THREAD

**Issue by alexcroox** [Nickersoft/push.js#21]
I'd like to show a 5 second count down in a notification (5...4...3...2...1).

I can currently replace the notification by creating a new one with the same tag, however this animates each notification in and out making it hard to read/click. Is there a way around this?

**Comment by Nickersoft** [comment]
Looking through the official [Notifications API documentation](https://developer.mozilla.org/en-US/docs/Web/API/notification), there does not seem to be a way to modify an existing notification. Without a direct API-supported function, I see no way Push could inherently add this functionality.
