### ISSUE TITLE
onClick function is not working on page reload

### ISSUE THREAD

**Issue by anshumansworld** [Nickersoft/push.js#210]
I created a notification and supplied `onClick` method in it. It works perfectly if I stay on the page. When I refresh the page and click on the notification, it opens a tab having URL only origin (i.e. window.location.origin).
```
onClick: function(data) {
  window.focus();
  window.location = data.target.tag; // I'm passing complete URL in tag
}
```

**Comment by theLufenk** [comment]
When you reload the page, you are destroying the browsing context. In other words, there is no `window` object available to execute the functions specified. 
You might want to look into service workers and handling notification click events inside a service worker.

**Comment by exzizt** [comment]
@theLufenk Will the service worker provided in Push.js achieve this?
