### ISSUE TITLE
NPM package outdated?

### ISSUE THREAD

**Issue by maxcoe** [Nickersoft/push.js#211]
It seems the NPM package is still in version 1.0 (or at least older than 1.0.9) because when using it in Safari 12 it throws an error that is actually fixed in the Github 1.0.9 version (Safari's window.Notification.requestPermission() needing a callback instead of returning a promise). 

Also the credits in the file push.js say "Push v1.0.9" in the Github version but "Push v1.0" in the NPM version, even though the NPM package pretends to be v1.0.9...

**Comment by theLufenk** [comment]
@Nickersoft 
Can you please bump the NPM release.

**Comment by potty** [comment]
Version 1.0.9 doesn't contain the Safari 12 fix. The commit was added after 1.0.9 release. @Nickersoft can you please release a new update with the Safari fix? You can see the error on pushjs.org page when you open it in Safari 12 and click on "View Demo" button.

**Comment by Nickersoft** [comment]
@potty @maxcoe Just released a new version.. hopefully there aren't any major issues with the release. I'm aware there are quite a number of detected NPM vulnerabilities in Push's dependencies, so be careful when using the package. I've been trying to upgrade the dependencies, but it's breaking tests and I need to investigate. Going to try to this weekend.
