### ISSUE TITLE
Notification is closing itself

### ISSUE THREAD

**Issue by APresman** [Nickersoft/push.js#216]
I need the notificaion to stay it open until user close it and not closing automatialy after some time. 

Both requireInteraction: true and timeout: XXXXXXXX  seems not to work by me (FF 56 and Chrome 75). The notification windows closes itself after about 15 seconds.

```
<script src="//code.jquery.com/jquery-latest.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/push.js/1.0.12/push.js"></script>
<script>
       Push.create("Hello from SIS", {
            body: event.data,
            icon: "/framework/icons/logo_mini.png",
            timeout: 1000000,
            requireInteraction: true,
            onClick: function() {
                console.log(event.data);
            }
            });
  
</script>
```

I'm not sure if FF does support  requireInteraction: true .
But also timeout isn't working to me.

**Comment by theLufenk** [comment]
Firefox doesn't support [`requireInteraction`](https://developer.mozilla.org/en-US/docs/Web/API/notification/requireInteraction) and yields no control over how long the notification will be visible. `timeout`is an internal construct of Push.js which calls `notification.close` after the specified time.
