### ISSUE TITLE
Add missing 'badge' option

### ISSUE THREAD

**Issue by byzyk** [Nickersoft/push.js#229]
I've noticed that `badge` option is missing, while it's widely supported according to [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification). Are there any plans on adding this? I can try to submit a PR in the next couple of days if you find it necessary to add.

BTW, thanks for such an incredible lib! Was able to save a tremendous amount of time while implementing notifications 👍🏽

**Comment by theLufenk** [comment]
Hello @byzyk 

Thank you for the kind words. 
A PR would be absolutely welcome :)
