### ISSUE TITLE
how can i send notifications for ios safari?

### ISSUE THREAD

**Issue by jarl-alejandro** [Nickersoft/push.js#233]
I can receive notifications on the web as in android using in magnificent library but in safari ios no council works

**Comment by theLufenk** [comment]
Hello @jarl-alejandro 

What seems to be the problem with safari ?
You would use Push.js in the very same for across all browsers. The library takes care of cross-browser compatibility under the hood and abstracts away almost everything.

Could you please try opening the [pushjs.org](https://pushjs.org) website and confirming whether the Demo works for you ?

**Comment by theLufenk** [comment]
@jarl-alejandro Sorry I missed the 'IOS' part of your question. IOS Safari has no implementation for Web push notifications yet.
