### ISSUE TITLE
Re-implement gulp as primary build tool

### ISSUE THREAD

**Issue by Nickersoft** [Nickersoft/push.js#24]
Gulp was removed a few commits ago and replaced by npm build scripts to simplify the build process. However, the list of npm scripts has become rather long and gulp should be used to remedy this. One issue that currently stands is the removal of the license comment in the minified version. Though technically fixable using NPM, Gulp can fix this using the gulp-uglify package and will require fewer dependencies overall.

**Comment by sarbbottam** [comment]
Reverting https://github.com/Nickersoft/push.js/pull/6 should be good.

**Comment by Nickersoft** [comment]
Resolve by commit 6e3aac2fe6ba8121dd4754643756c96a20721ba7
