### ISSUE TITLE
Push.js keeps asking for permission in Chrome even after "allow" is pressed.

### ISSUE THREAD

**Issue by NamanSharma5** [Nickersoft/push.js#246]
I require a simple desktop notification on a button press but each time I press the button, it repeatedly asks for permission and  does not display the push notification. Upon checking Push.Permission.has(), I find the boolean returns false even when I repeatedly press allow on the chrome permission request. I am using push.min.js and serviceworker.js in my directory and referring to them in a script tag in the html document. I have tried using push.js without serviceworker.js but have had no success.

What do I do? How can I fix this?

Thank you for reading this.

**Comment by aguileraq** [comment]
Hi @NamanSharma5. try to start a node server and run your app or try with Firefox, in Chrome you need to start a node server and i think you need a ssl certificate. i hope this info can help you. bye

**Comment by theLufenk** [comment]
@NamanSharma5 
Please specify the browser you are testing on. 
Are you testing on localhost, or is there a url we can visit to see the issue ?
Also it would help if you can make a jsfiddle to demonstrate your issue, incase of the former.
Thanks

**Comment by NamanSharma5** [comment]
@aguileraq Thank you for your help. I will try to run a node server. Do you know if there is any other way to create push notifications in chrome?
Also, in Microsoft edge, no notifications appear even after I grant permission.  Although, unlike chrome , Microsoft Edge only asks for permission once, when the page starts.

I have attached screenshots of the source code.
![javascript code for push js test](https://user-images.githubusercontent.com/46360561/78050300-f52cab00-7373-11ea-9ac0-14dc714d9d3e.JPG)
![html code for push js test](https://user-images.githubusercontent.com/46360561/78050306-f5c54180-7373-11ea-8c58-3bb368fe0262.JPG)

**Comment by NamanSharma5** [comment]
@theLufenk Thank you for your response.
I am testing on Google Chrome, on which it keeps asking for permission.
In Microsoft edge, the notifications do not appear after granting permission to the webpage.
It works fine in Firefox- is there a way to stop firefox from showing the warning about "prevent this page from creating additional dialogues"
I have attached the code in my response to @aguileraq

**Comment by NamanSharma5** [comment]
@aguileraq @theLufenk 
Thank you for responding to my initial query, your support has been invaluable towards my project.
