### ISSUE TITLE
Uncaught (in promise) PushError: permission request declined

### ISSUE THREAD

**Issue by makyo5** [Nickersoft/push.js#247]
I Build a project, and I put the dist on the server.
I use the NGINX to deploy the project, location is html/myproject, the file is index.html.
But I visit the address, the push does not come out. The exception is :
Uncaught (in promise) PushError: permission request declined.
I found that the permission is not granted in the beginning.

( I put the "Push.Permission.request()" in the main.js, but couldn't grant the permission after all.
)

**Comment by theLufenk** [comment]
@makyo5 Clearly the push permission has been denied for the domain. The browser doesn't asks for permission again after it has been denied or accepted once.

Or maybe reset the notification permission for your domain in the browser.
I would suggest testing in a different browser or system to see if it works.

You didn't mention the browser, but [ here's how you could do it for Chrome](https://support.google.com/chrome/answer/114662?co=GENIE.Platform%3DDesktop&hl=en)

**Comment by makyo5** [comment]
Thx for your advise, the permission of this address is allowed... 
I reset the permission, but I wonder why the asking for permission does not appear.
And... I set allow prop on this site, but always Push.Permission.get() showes denied.


(I found the chrome says my site is "Not secure")

**Comment by makyo5** [comment]
I change to Firefox, ant console says:
The Notification permission my only be requested in a secure context.

**Comment by makyo5** [comment]
I found this function worked in other client......
So I consider this is my pc's prblem. I reset the chrome option and reinstall... still occures....
thx for helping....

**Comment by theLufenk** [comment]
There's your answer. Your webpage needs to be served over **https** as notifications are not allowed in **http** contexts.

**Comment by makyo5** [comment]
Thx! The push.js is very good. I will fix the http problem for using the push.js.
