### ISSUE TITLE
usage of push.js with angularjs

### ISSUE THREAD

**Issue by Rafi993** [Nickersoft/push.js#26]
Can push.js be used with angular 1.X.  Example for such usage may be included

**Comment by Nickersoft** [comment]
I've never used Angular before, so I cannot vouch for its compatibility. Perhaps someone else can comment, or you can give it a go and see if it works. If it's just plain JavaScript, I see no reason it shouldn't work :)

**Comment by jdrew1303** [comment]
Hey @Rafi993 

To use it with Angular 1.x you will need to include the script as normal. I'd recommend before loading it before your app if you use just script tags. If you're using browserify or webpack then you'll need to install it from npm  :
`https://www.npmjs.com/package/push.js`

Then import it as necessary in a wrapper module: 
``` javascript 
var Push = require('push.js'); // Common.js
import * as Push from 'push.js'; // if using ES6 

angular.module('push.js', []).factory('Push', [function() {
    return Push; 
}]);
```

Then add push to your app: 
``` javascript 
angular.module('app', ['push.js'])...
```

You should be able to use this as normal by injecting in `Push` and following the readme.

Hope this helps 😃 

Also @Nickersoft Great lib! Keep up the good work! 👍

**Comment by Rafi993** [comment]
Thanks for the help
