### ISSUE TITLE
Notification support for mobile devices

### ISSUE THREAD

**Issue by rickgoud** [Nickersoft/push.js#34]
Great project!
However the description suggests support for all devices.
However it does not work on mobile devices. You do get the request the allow notifications, but a notification is never sent.
Is this support anticipated soon?

**Comment by Nickersoft** [comment]
Theoretically, it should work cross-platform, but mobile devices were never tested. I actually started this project to complement a desktop-oriented website I was building, so I never thought of testing it on phones. However, now that more people are using it, I'll definitely look into what the issue might be.

**Comment by Nickersoft** [comment]
Currently investigating this issue on mobile Chrome (Android N). It seems to be throwing the following error:

```
Uncaught TypeError: Failed to construct 'Notification': Illegal constructor. Use ServiceWorkerRegistration.showNotification() instead.
```

As it turns out, mobile Chrome does not support the `new Notification()` constructor (as it is being depreciated) and instead requires a service worker. Some justification as to why can be [found here](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/BygptYClroM). This should be a fairly straight-forward fix though. Working on a fix :)

**Comment by Nickersoft** [comment]
A quick update on this issue: apparently the new ServiceWorker approach requires the host site to use SSL in order to function properly. SSL is enabled on the GitHub page, but I'm trying to get a local SSL server running to test before I commit anything.

**Comment by Nickersoft** [comment]
Exciting news! Mobile chrome support was just added with 4edcc9d6ec16476378c33a829efb7c82bbdb5631. You can even make the device vibrate when you get a notification :) Enjoy! Let me know if you run into any bugs. Closing this for now.

**Comment by rickgoud** [comment]
Great! You're fast! :)
Is it correct that the demo wasn't updated yet? At least it doesn't work there.
Did you also test is on other mobile browsers (Safari, etc).

Thanks!

**Comment by Nickersoft** [comment]
Apparently mobile Safari doesnt even have the ability to send push notifications, so it was not tested. And the demo was updated, although the site needs to be using a valid SSL certificate in order for it to work properly (something mobile Chrome requires, not me). So try [https://nickerson.github.io/push.js/demo.html](https://nickerson.github.io/push.js/demo.html).

**Comment by rickgoud** [comment]
Great! It works on Android. However on IOS on an Iphone it still doesn't work. Would be great if that is supported as well! You rock!

**Comment by Nickersoft** [comment]
Haha thanks. As I said, Safari on iOS does not support the Notifications API (which sucks I know), so until it does there's nothing I can do about it :/

**Comment by rickgoud** [comment]
Apologies, I ment Chrome on IOS.. :)

**Comment by Nickersoft** [comment]
Just checking now, it seems that the Notifications API in general is not supported on iOS, in neither Chrome or Safari. According to [this Verge article from last year](http://www.theverge.com/2015/4/20/8454613/push-notifications-android-chrome-42-mobile-web), Chrome still cannot send push notifications on iOS. Looks like Apple will once again need to play catch-up with Google.

**Comment by ppumkin** [comment]
Damn iOS always has to complicate everything.

**Comment by alimaaz** [comment]
On my mobile notification not shown.
