### ISSUE TITLE
allow (sanitized) html tags for body

### ISSUE THREAD

**Issue by gebrits** [Nickersoft/push.js#35]
Is it possible to allow a subset of html tags for the message body? Currently tags are just displayed as text

**Comment by Nickersoft** [comment]
According to the [official docs](https://developer.mozilla.org/en-US/docs/Web/API/Notification/body), it seems that the body attribute is simply a string that does not resolve any HTML tags. Unfortunately, there is nothing Push itself can do to change this, as its just a robust shim wrapper around the native API calls.

**Comment by gebrits** [comment]
ok that explains it.
