### ISSUE TITLE
How can we use the library for GCM push messages?

### ISSUE THREAD

**Issue by aniljaiswal** [Nickersoft/push.js#37]
I'm looking for a way to integrate the library to allow GCM push notifications to be able to show messages on both desktop and mobile chrome browser. 

Is it possible currently? If yes, how do I do it?

**Comment by andy318** [comment]
You are asking about Push notifications which work even if the user does not have a browser tab open to the website. That is different from Web notifications which only work if there is a tab open to the website. 
This library is only concerned with the latter.

**Comment by Nickersoft** [comment]
Sorry for the late response... I actually don't know too much about GCM, so perhaps another contributor might be able to better answer this question. I have not tested the library with GCM or used it before.

**Comment by dmitry-korolev** [comment]
Actually no, because Push.js has nothing to do with Web Push API. I have to notice that 'Push.js' is a very confusing name for this library.

**Comment by Nickersoft** [comment]
Hi guys! I know this issue going on a year old, but I just wanted to let you know that Push.js is currently on the road to v1.0, complete with third-party plugin support. I'm in the process of putting the finishing touches on the first ever plugin, which happens to be for Firebase/Google Cloud Messaging! It isn't published yet, but I thought I'd let you guys know. I didn't forget about you! You can check out the plugin here:

https://github.com/Nickersoft/pushjs-fcm-plugin

**Comment by aniljaiswal** [comment]
This is such an awesome news man. I can't wait for you to finish the
plugin.

On Jun 15, 2017 11:07 PM, "Tyler Nickerson" <notifications@github.com>
wrote:

Hi guys! I know this issue going on a year old, but I just wanted to let
you know that Push.js is currently on the road to v1.0, complete with
third-party plugin support. I'm in the process of putting the finishing
touches on the first ever plugin, which happens to be for Firebase/Google
Cloud Messaging! It isn't published yet, but I thought I'd let you guys
know. I didn't forget about you! You can check out the plugin here:

https://github.com/Nickersoft/pushjs-fcm-plugin

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Nickersoft/push.js/issues/37#issuecomment-308799310>,
or mute the thread

**Comment by Nickersoft** [comment]
Good news guys! Push v1.0 and the FCM plugin are OUT! 

```bash
$ npm install push.js --save
$ npm install push-fcm-plugin --save
```

Read the docs on using FCM with Push [here](https://github.com/Nickersoft/pushjs-fcm-plugin).

**Comment by aniljaiswal** [comment]
Woohoo! The wait is finally over.

Best,

Anil
