### ISSUE TITLE
add build to npm so we use from cdn

### ISSUE THREAD

**Issue by luisrudge** [Nickersoft/push.js#4]
https://npmcdn.com/push.js@0.0.1
https://npmcdn.com/jquery@2.2.3

**Comment by sarbbottam** [comment]
Please see #6, `"prepublish" : "npm run build` should address the issue.

**Comment by sarbbottam** [comment]
[should the build directory be named `dist` instead of `bin`?](https://github.com/Nickersoft/push.js/issues/7)
