### ISSUE TITLE
Good admin area example?

### ISSUE THREAD

**Issue by 2braincells2go** [Nickersoft/push.js#44]
I cannot call this an issue, but wondering if you could point me to good tutorial on setting up (admin) area to actually push the messages? 

Wanting to use this in school classroom but like to learn more about using first. Hate to have a kid call me out on it:)

Thanks in advance for your input.

Woody

**Comment by Nickersoft** [comment]
Could you elaborate on what you mean by admin area?

**Comment by 2braincells2go** [comment]
Hi Tyler. Thank you for replying.

Looking for simple way to send the actual push message. Maybe simple form? Since many of the students are in 12-16 year old range, looking to make things very simple.

Totally understand this is out of scope, but just hoping for some more in-depth tutorials and maybe working examples.

Cheers,

Woody

**Comment by Nickersoft** [comment]
Depending on what you hope to achieve, you could just wire a button to send the message using the [onclick() method](http://www.w3schools.com/jsref/event_onclick.asp). So it might look something like:

```html
<button onclick="Push.create('Hello World');">Click me</button>
```

Hopefully this is along the lines of what you're looking for?

**Comment by 2braincells2go** [comment]
Thanks again Tyler for input.

Yes something like that but, with form so message can be customized.

I tried onclick method very similar to what you show but also ran into problem of not working. Was on server when tried. Will review my code tomorrow at school and see if yours fixes issues.

Just looking for form that message is customized and submit button so very close:)

Cheers!

**Comment by Nickersoft** [comment]
Oh, okay! You could always just do something like this (untested):

```html
<form onsubmit="func();">
    <input type="text" id="name" />
    <input type="submit" value="Submit" />
</form>
<script type="text/javascript">
     function func() {
          Push.create(document.getElementById("name").value);
     }
</script>
```

For more information of HTML forms, [see here](http://www.w3schools.com/html/html_forms.asp). Hopefully this is a little more helpful.

**Comment by 2braincells2go** [comment]
Hi Tyler. Sorry for no reply, been kind of crazy with end of year, school is out for summer.

Appreciate the input and will be exploring some ways to do an admin area over the summer.

Cheers!

**Comment by Nickersoft** [comment]
No problem. I closed this issue because I hadn't heard from you and figured you had everything sorted out. If you have any further questions, just feel free to post on this issue and I'll reopen it :)
