### ISSUE TITLE
No CDN?

### ISSUE THREAD

**Issue by thatoneguy107** [Nickersoft/push.js#45]
I tried to use the github raw text, but it interpreted it as plain text, so i would appreciate a link to a cdn for my webpage.

**Comment by Nickersoft** [comment]
I have not personally tested this, but Push is available on CDNJS:

[https://cdnjs.com/libraries/push.js](https://cdnjs.com/libraries/push.js)

(or if you don't feel like visiting the link, just use https://cdnjs.cloudflare.com/ajax/libs/push.js/0.0.8/push.min.js for version 0.0.8, which is the latest release).

Also, I thought I tried using Github raw text and it worked. Just out of curiosity, how were you implementing it?

**Comment by thatoneguy107** [comment]
I used "<script type="text/javascript" src="https://raw.githubusercontent.com/Nickersoft/push.js/master/push.min.js"></script>" (without quotes)

**Comment by Nickersoft** [comment]
Hmm, yeah, testing now I see that is doesn't seem to work. It might have to do with the fact the library is wrapped in one big self-executing function. Regardless, there is a CDN for it so I hope it works for you :)
