### ISSUE TITLE
problem with webpack

### ISSUE THREAD

**Issue by YannickBochatay** [Nickersoft/push.js#46]
Since the minified version contains Promise polyfill, it doesn't fit well with webpack (and I would tell browserify neither) : 

`import Push from "push.js"`

The Push object contains Promise instead of Push constructor.
This can be fixed in the package.json : the main file should be push.js and not push.min.js which is the "standalone" version.

**Comment by Nickersoft** [comment]
Should be a relatively quick and easy fix. I was actually considering removing the polyfill in a future version, as promises are [decently supported](http://caniuse.com/#search=promise) and if users want to maintain support for older browsers they can use the polyfill separately. When I added the polyfill, I thought it would be a useful addition to the library, but seeing now how it is really only IE that lacks support for promises, it seems foolish to add all that extra weight. Anyway, like I said, this should be a quick fix and I'll open a PR for it as soon as I can :)

**Comment by Nickersoft** [comment]
This problem should be resolved with cae24c6bde4928fe2d880f77c4c101d208ac29db. I removed the polyfill dependency and updated the main file in package.json.

**Comment by thesabbir** [comment]
please update npm package :)

**Comment by Nickersoft** [comment]
Done :) Closing this issue for now
