### ISSUE TITLE
does the push API work from an extension / background page? 

### ISSUE THREAD

**Issue by gebrits** [Nickersoft/push.js#5]
Does push api work in a chrome extension / background page?

**Comment by Nickersoft** [comment]
Theoretically, seeing it is just using the underlying Javascript Notifications API and Chrome extensions are just plain Javascript. That said, I have never written a Chrome extension before and have not tested this, so I do not know for certain. You're welcome to give it try. I see no reason it shouldn't work :)

**Comment by gebrits** [comment]
Cheers I'll give it a try soon :)
