### ISSUE TITLE
Why don't you update npm package more regularly?

### ISSUE THREAD

**Issue by thesabbir** [Nickersoft/push.js#54]
#50 seems to be a big bug which should have been updated already.

**Comment by Nickersoft** [comment]
This bug should have been fixed in [v0.0.10](https://github.com/Nickersoft/push.js/releases/tag/v0.0.10)

**Comment by thesabbir** [comment]
Github tags/release wont automatically publish the package in npm.
You need bump the version number in `package.json` then publish it via `npm publish`

**Comment by Nickersoft** [comment]
Hmm.. that tag should have been created as a result of publishing the package. Something must have gone wrong during the publishing process, and I guess I didn't notice the fact the version number didn't update in package.json. Will fix ASAP :)

**Comment by Nickersoft** [comment]
So for some reason the version commits for v0.0.10 never got pushed. Just pushed them now and the version is correct on [the NPM site](https://www.npmjs.com/package/push.js). Sorry bout that!
