### ISSUE TITLE
Display page onClick

### ISSUE THREAD

**Issue by itsChimpanzee** [Nickersoft/push.js#55]
I'm sure this is very simple so apologies for the stupid question, but how does one simply display the page that triggered the notification when the user clicks on it? I see there's an onClick option to execute a some js, but I don't actually need to do anything except re-focus the browser and go to the appropriate tab. I don't need to execute any js on the page.

Thanks in advance.

**Comment by Nickersoft** [comment]
So I just recently got this working myself after some fiddling, and this code is now live on the official [Push demo](https://nickersoft.github.io/push.js/demo.html):

```
            Push.create('Hello world!', {
                body: 'This is an example string',
                onClick: function () {
                    window.focus();
                    this.close();
                }
            });
```

Should work. Let me know if you run into any issues 😃

**Comment by itsChimpanzee** [comment]
Works perfectly! Thank you so much :)

**Comment by Nickersoft** [comment]
No problem 😄
