### ISSUE TITLE
Possibility to detect first permission invocation

### ISSUE THREAD

**Issue by luknei** [Nickersoft/push.js#58]
Hello guys,
Thanks for awesome library!
I have a feature request to show a dialog explaining what notifications will be sent to the user. I could not find similar example in the examples. Is there a way to know if permission popup is opened before calling Push.create?

**Comment by Nickersoft** [comment]
Sorry for not commenting on this sooner.. are you trying to display a dialog before Push requests permission from the user? Could you elaborate?

**Comment by luknei** [comment]
Hey! Well turns out it's pretty simple. Push instance has property of Permission property which contains method of accessing current permissions status and possible types. Code for checking if notifications confirmation will be shown:
```
function willAskForPermission() {
    return Push.Permission.get() === Push.Permission.DEFAULT;
}
```

**Comment by kokarn** [comment]
Just adding this for the future, if you want to request access without creating a notification this is how i did it
```
if ( Push.Permission.get() === Push.Permission.DEFAULT ) {
    Push.Permission.request();
}
```
