### ISSUE TITLE
will this work when the webapp is in the background on mobile ? (question)

### ISSUE THREAD

**Issue by jasan-s** [Nickersoft/push.js#64]

**Comment by Nickersoft** [comment]
Seeing the service worker isn't actively pulling from a backend, and is implemented for the sole purpose of allowing local notifications on mobile Chrome, I don't believe it will. However, I just had someone ask me a similar question, so you might find the answer useful. Attached is a screenshot of that convo.
<img width="615" alt="screen shot 2016-08-11 at 10 38 43 am" src="https://cloud.githubusercontent.com/assets/2104129/17592857/fb6b9bc2-5fb1-11e6-8ef4-0a2527dd6b63.png">
