### ISSUE TITLE
notification.close "undefined"

### ISSUE THREAD

**Issue by AndrewsVinicius** [Nickersoft/push.js#66]
Hey! Great plugin, but i found some issue.
I close a tab manually and when the notification timeout i have a "undefined" to the notification[id]. Becouse i close the notification, and that id still undefined in the array.

To bug fix i just add:
> if (typeof(notification) === "undefined") {
>   return false;
> }

At the function "closeNotification = function (id)".

Thanks :D

**Comment by DiscoTim** [comment]
duplicate https://github.com/Nickersoft/push.js/issues/65

**Comment by Nickersoft** [comment]
Commit 26387abffd7da39736f6c3a24440fd70178c4d9e just fixed this issue using code similar to yours. Closing ticket.
