### ISSUE TITLE
TypeError: Cannot read property 'addEventListener' of undefined"

### ISSUE THREAD

**Issue by DiscoTim** [Nickersoft/push.js#69]
Hi, receiving this error on chrome mobile from the demo site.

08-22 01:07:33.115: I/chromium(32495): [INFO:CONSOLE(38)] "Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of undefined", source: https://nickersoft.github.io/push.js/push.min.js (38)

I think it is because if it uses the service worker method, notification does not get defined.

its related to this issue https://github.com/Nickersoft/push.js/issues/68

but i don't expect the events to work, those need to be done from within the service worker, for myself i just need it not to error getting the service worker loaded.

**Comment by Nickersoft** [comment]
A fix is on the way for this. For sake of simplicity, I'm going to post all updates on this fix to #68. Closing this for now.
