### ISSUE TITLE
IOS compatability

### ISSUE THREAD

**Issue by DiscoTim** [Nickersoft/push.js#71]
Has this library been tested or working  on IOS chrome or safari? or does it work with any browser on ios?

**Comment by acierto** [comment]
Doesn't work on Safari for sure, just wanted to raise an issue about that :)

**Comment by DiscoTim** [comment]
according to this https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/Introduction/Introduction.html I'm thinking its not possible, but I'd like a definitive answer.

**Comment by Nickersoft** [comment]
In the "Mobile Support" section of the README, I mention how mobile notifications currently aren't supported on iOS. [Here is](https://onesignal.com/blog/when-will-web-push-be-supported-in-ios/) a nice blog post going into more detail about it from 2015. Unfortunately, the ball is in Apple's court with this one.

**Comment by DiscoTim** [comment]
I did read that post but its somewhat confusing the state of things, as they mention chrome and firefox does support them,  which are available for iOS. In the link I provided it mentions "Notifications for websites do not appear on iOS." I am finding it fairly difficult to find information on it :) I am assuming no browser on iOS will display notifications, and only native apps are capable of it.

**Comment by luckylooke** [comment]
There should be a simple fallback for IOS, popup or whatever.

**Comment by nickmask** [comment]
Does not work for IOS, neither Chrome nor Safari as apple force Chrome to use Safari’s render engine (webkit) :(
