### ISSUE TITLE
Do you plan to add functionality that allows offline web socket receive messages and display them?

### ISSUE THREAD

**Issue by player0k** [Nickersoft/push.js#73]
some functionality like facebook pushes

**Comment by Nickersoft** [comment]
In version 1.0.0. of Push, I'm going to investigate the possibility of extending it to support Google Cloud Messaging, which will allow this sort of functionality. Unfortunately I've been very busy lately, so I'm not sure when this might be implemented. I'll continue to post updates as work on Push continue though!

**Comment by Basilakis** [comment]
Interested on that also.
If we can " fund " the development in any way, I Will be glad to do it.

**Comment by theLufenk** [comment]
@Nickersoft has been generous enough to write a [plugin for FCM](https://github.com/Nickersoft/push-fcm-plugin) .

For people you might find themselves in a similar situation, please refer to the [PLUGIN DOCS](https://pushjs.org/docs/plugins). It is a neat way to expand upon the functionality provided by Push.js.

A Feature Request/Pull Request is always welcome.
