### ISSUE TITLE
Does this library work on NodeJS or any server side?

### ISSUE THREAD

**Issue by ViniciusTavares** [Nickersoft/push.js#76]
Hello guys! 

I've been implemeting notifcations on browser in my project, but I have to do that using a server side. I coudn't find any solution for it using this library to access my service worker from NodeJS, for instance.  

Is it possible using push.js?

Hugs.

**Comment by TangMonk** [comment]
absolutely not

**Comment by Nickersoft** [comment]
It currently does not, but I plan on looking into supporting GCM/server-side push notifications in the future :)

**Comment by ViniciusTavares** [comment]
Thanks for the messages, guys! :)
