### ISSUE TITLE
A bug in IE9+ when create notification

### ISSUE THREAD

**Issue by ecmadao** [Nickersoft/push.js#78]
Hey @Nickersoft, thanks for your useful notification plugin.
I'm recently reading your source code to learn Notification API, and maybe I find a small mistake in your code.

in [push.js, line 240~249](https://github.com/Nickersoft/push.js/blob/master/push.js#L240~L249), 

``` javascript
// Clear any previous notifications
w.external.msSiteModeClearIconOverlay();
// ....
notification = {};
```

I notice you clean other notification before create new in IE9, so maybe what you wanna do is:

``` javascript
notifications = {};
// not notification = {};
```

Otherwise, It will throw an error when you `addEventListener` later.

Besides, I have opened a [pull request](https://github.com/Nickersoft/push.js/pull/77) for this small bug. THX.

**Comment by Nickersoft** [comment]
See the comment left on the pull request. Closing.
