### ISSUE TITLE
Documentation adjustment

### ISSUE THREAD

**Issue by tucson-tom** [Nickersoft/push.js#81]
The demo nor any of the documentation shows how to detect what the current state of permissions is.  I had to dig around in the Push.js source code to find a function.

Push.Permission.get() appears to be the method that retrieves the cross-browser permission level.  Since the function doesn't appear to be called internally by Push.js, I can only assume that it is meant to be used by application code and calling the functions does appear to work as expected.  However, assumptions aren't as good as documentation.

**Comment by Nickersoft** [comment]
Hey there! I apologize for not getting around to this until now. Just added this info to the README with commit 9716db297b669bcd8b3471eeb2e54607bbe6dd0b. Not sure why I didn't include it originally. Happy holidays!

**Comment by tucson-tom** [comment]
The additions look great.  Thanks!
