### ISSUE TITLE
please help me how we triger the notification using php with API

### ISSUE THREAD

**Issue by srinivasan** [Nickersoft/push.js#83]
Hi

Please help me how we trigger the message from background using php API.

Thanks

**Comment by srinivasan** [comment]
How we get the registed devices list please help me

**Comment by Nickersoft** [comment]
Push.js cannot inherently handle messages from any backend server yet.. however, this question has been raised before, so check out the response on that issue (#73). The best you'd be able to do currently is write an AJAX call on the front-end that long polls the server, then calls Push new information is received. I apologize for the inconvenience, but I assure I plan on looking into it.
