### ISSUE TITLE
how to setup Service Worker?

### ISSUE THREAD

**Issue by itayganor** [Nickersoft/push.js#93]
Hey,
Can you please help me with installing and using the service worker?
I need push.js to send notifications to mobile, and enable clicking on the notifications, and by the internet I need a service worker for that.
I googled it but nothing seems to be helpful.

thanks! 😄

**Comment by Nickersoft** [comment]
Hey, thanks for using Push! To use mobile notifications with Push, first make sure `serviceWorker.js` and Push are in the same directory. Also make sure the site you're running it on uses SSL. If you don't have SSL on your server you can always grab a cert over at https://letsencrypt.org. Then to create mobile notifications, just call Push as you normally would. If you want to have the notification open a certain page on your site when clicked, check out the `link` option in the README. If you want a custom click event, check out the `onClick` option. Let me know if this helps or if you have any other questions.

**Comment by iTayGNR** [comment]
What code does the `serviceWorker.js` file should have in order to send Push notifications when the website is not open or on mobile?

**Comment by Nickersoft** [comment]
Push notifications without the website being open are still in the works. Currently Push's code must be called from an open window. The serviceWorker.js file packaged with the repo contains code that handles the `link` option, as well as click and close events for mobile notifications.

**Comment by iTayGNR** [comment]
where can I find this code/explanation of what should this file include?
thanks :)

**Comment by Nickersoft** [comment]
serviceWorker.js already contains all the code required for it to run correctly, it just needs to be in the same directory as the push.min.js file. You can read more about how to pass data to the service worker in the "Available Options" section of the [README](https://github.com/Nickersoft/push.js#available-options)

**Comment by ellisio** [comment]
Hey, any progress update on closed window push notifications for this library? We love this package as it has a simple API to use, but the biggest complaint we are getting from our users is they don't get push notifications like other websites when they are expected.

I'd love to help, but I don't even know where to begin to get this functionality working.

**Comment by Nickersoft** [comment]
Oh hey @ellisio! Guess you haven't heard... version 1.0 of Push has dropped, and the biggest new feature is support for third party plugins. I wrote the first plugin, which adds support for Firebase Cloud Messaging, which DOES allow for closed window notifications! You can check out the docs and install info [here](https://github.com/Nickersoft/push-fcm-plugin). It seems like word about this isn't getting out that well... so if you know anyone else who uses the library, be sure to let them know too! I might post to Hacker News or something about it. Also, [net magazine](http://www.creativebloq.com/net-magazine) is publishing a tutorial in their September issue about how to hook FCM up with Push, so keep your eye open for it if that's your sort of thing. I'll probably write a blog post about it eventually. Anyway, yeah! Check out the plugin and let me know if you have any questions :) Thanks for using Push.

**Comment by pwFoo** [comment]
I'm searching for a lib with closed window push without third party plugin. 
So push.js won't work die me?

**Comment by smeijer** [comment]
Examples would be useful, as I currently feel that `push.js` is no replacement for `web-push`. Perhaps incorrectly?

**Comment by matronator** [comment]
> serviceWorker.js already contains all the code required for it to run correctly, it just needs to be in the same directory as the push.min.js file. You can read more about how to pass data to the service worker in the "Available Options" section of the [README](https://github.com/Nickersoft/push.js#available-options)

What about when installed with npm? Where should the SW file be then?
