### ISSUE TITLE
Notification icon doesn't work for Sfari

### ISSUE THREAD

**Issue by yofret** [Nickersoft/push.js#94]
Hi guys, I'm trying to do a simple implementation for this library, it works perfectly, but the Icon doesn't quite work for Safari, It works for Chrome and Firefox

this is my code

```
Push.create(header, {
    body: body,
    icon: {
        x16: 'images/assets/test_16.png',
        x32: 'images/assets/test_32.png'
    },
    timeout: 8000,
    onClick: function () {
        window.focus(); // navigate to window
        this.close();
    }
});
```

**Comment by Nickersoft** [comment]
So looking over the [Safari Local Notifications documentation](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/LocalNotifications/LocalNotifications.html#//apple_ref/doc/uid/TP40012932-SW1), it doesn't look like Safari supports icons in notifications (something that was previously unknown to me). Safari supports the "tag" and "body" options exclusively, as well as notification events. Unfortunately there's not much I can do to change that :/

**Comment by yofret** [comment]
Oh man :/, Thanks for checking out this issue, this icon issue is giving hard times, only in safari
