### ISSUE TITLE
Send to who subscribed

### ISSUE THREAD

**Issue by Ciao121** [Nickersoft/push.js#97]
Hi,
I installed the code and it's working but I do not understand.
I would like to send a message to all users that enabled notifications on my site.

But here I do not see nothing like a subscribers saving feature. So how can I have a "list" of all subscribed users to use to send out a message?
Maybe is not a feature of this software...
Can someone help me to understand how to do this?

Thank you!!!

**Comment by Nickersoft** [comment]
Unfortunately, Push does not save any data regarding the websites it runs on or the users who enable its notifications. This sounds like functionality that would come from server-side push notifications, which is something this library does not currently support. Hopefully it will in the future though :)

**Comment by kevzlou7979** [comment]
+1 Might have a feature to specify which user will be receiving a notification.

**Comment by pwFoo** [comment]
Is it possible to get the browser subscription and send it to the server to use it for push notifications to custom users?
I'm new with web notification / pushjs and searching for a user based notification withour third party plugins / servers involved.

**Comment by theLufenk** [comment]
Getting permissions for Notifications and sending a Server Side push to device, though related, are two different things.

Push.js is intended to assist your web application in acquiring permissions and creating Notifications in a web browser.

Being able to send targeted Push notifications from server side entails using the PushManager provided by the ServiceWorker registration to subscribe the user and obtaining a subscription token.

A good starting point for reading about Server side push is [this guide by Google](https://developers.google.com/web/fundamentals/push-notifications/subscribing-a-user#subscribe_a_user_with_pushmanager)


You might want to look into [Push.js FCM plugin](https://github.com/Nickersoft/push-fcm-plugin) too if it its your use case.
