### ISSUE TITLE
Demo not working on mac OS sierra 10.12.2 and Chrome

### ISSUE THREAD

**Issue by GeorgiosP** [Nickersoft/push.js#98]
The demo on 
https://nickersoft.github.io/push.js/

does not work with chrome on mac 
OS: Sierra 10.12.2 
Chrome: 56

Works on Firefox and safari

**Comment by Nickersoft** [comment]
I'm running macOS Sierra 10.12.3 and Chrome 56 and the demo works fine for me.. is it throwing any errors in the developer console? This behavior might happen if you had previously disabled notifications in Chrome. You can check your notification settings by going to Settings / Privacy / Content Settings and scrolling down to "Notifications".

**Comment by GeorgiosP** [comment]
All notifications for the site are allowed, and there are no errors happening in the console, not sure what else it could be I only get a network response of Icon.png with a status code 200

**Comment by Nickersoft** [comment]
Hm.. when you run the demo, is Chrome in fullscreen mode? I know Chrome won't show notifications if it's full screen or presentation mode.

**Comment by GeorgiosP** [comment]
Interesting seems like that worked! when you're not in full screen, it does however work full screen on my windows machine is this a mac only thing?

**Comment by Nickersoft** [comment]
I believe it is a Mac-only issue, yes. Perhaps I should add something to the README about it.
